package: api
output: internal/generated/api.gen.go
generate:
  models: true
  chi-server: true
output-options:
  include-operation-ids:
    - createTrip
    - getTrip
    - finishTrip
    - health
    - ready
